export const L = {
  appTitle: "Авто-Рилс",
  sources: "Источники",
  clips: "Клипы",
  root: "Корень",
  loading: "Загрузка…",
  error: "Ошибка",
  noSources: "Источников нет",
  noClips: "Клипов нет",
  clipCount: (n: number) => `${n} кл.`,
  variant: "Вариант",
  mainVariant: "основной",
  back: "← Назад",
  backToSources: "← Источники",
  backToOverview: "← Обзор",
  variantsMore: (n: number) => `+${n} вар.`,
  help: "Клавиши",
  helpHint: "? — клавиши",
  close: "Закрыть",
  pickClip: "Выберите клип слева или нажмите J",
  overviewSummary: (clips: number, variants: number) =>
    variants > 0 ? `${clips} рилсов · ${variants} вар.` : `${clips} рилсов`,
  viewGrid: "Сетка",
  viewList: "Список",
  watchInOrder: "Смотреть по порядку",
  continueAt: (clip: string, t: string) => `Продолжить: ${clip} · ${t}`,
  colClip: "Клип",
  colTitle: "Заголовок",
  colDuration: "Длит.",
  colVariants: "Варианты",
  sizeLabel: "Размер",
  sizeNames: { s: "S", m: "M", l: "L" } as Record<"s" | "m" | "l", string>,
  rename: "Переименовать",
  renameHint: "Enter — сохранить, Esc — отмена, пусто — вернуть имя папки",
  folder: (stem: string) => `папка: ${stem}`,
  variantsCount: (n: number) => (n > 0 ? ` · ${n} вар.` : ""),
};
